# Site settings
title: École Montessori de Melun - Vaux le Pénil
email: contact@ecole-montessori-melun.fr
phone: "07 87 85 45 98"
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://www.ecole-montessori-melun.fr"
repository: "montessori-melun/montessori-melun"

# Permalinks
permalink: :year/:month/:title:output_ext

# Plugins
gems:
  - jekyll-sitemap

# Just for local server
port: 4321

# Markdown parsing
markdown: kramdown
kramdown:
  input: GFM
  header_offset: 1
  parse_block_html: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

exclude:
  - Gemfile*
  - README.md
  - LICENSE.md
include:
  - favicon.jpg
